### ISSUE TITLE
word2vec训练问题

### ISSUE THREAD

**Issue by quicksandznzn** [shibing624/similarity#18]
Word2vec.trainModel可以训练多个小文件嘛
可以把多个模型合成一个大模型嘛

**Comment by shibing624** [comment]
自己写个脚本拼接一下数据就可以。

**Comment by quicksandznzn** [comment]
嗯嗯 按照这样做了 但是训练大文件很容易卡死

**Comment by quicksandznzn** [comment]
@shibing624  Word2vec.getHomoionym 方法能否解释一下此方法的实现原理和可靠性 多谢
