### ISSUE TITLE
请问一直提示Cannot resolve io.github.shibing624:similarity:1.1.2-SNAPSHOT怎么办？

### ISSUE THREAD

**Issue by braveryCHR** [shibing624/similarity#19]
你好，不知道您的maven是否写错了，
一直提示：Cannot resolve io.github.shibing624:similarity:1.1.2-SNAPSHOT

**Comment by shibing624** [comment]
用离线jar包吧，见readme 版本是1.1.3    离线jar包 similarity-1.1.3-jar-with-dependencies.jar
