### ISSUE TITLE
词库扩展咨询

### ISSUE THREAD

**Issue by shibing624** [shibing624/similarity#2]
你好啊，github上搜到你的项目，相识度匹配等使用工具，正好项目中需要研究。不过需要请教下，我如何扩充 词库呢？
1.词林词库，目前是按照一个的格式存储在xml的，如何扩展？
2.同义词词库，一样的如何扩展？
3.义原词库，如何扩展？
望能指点下。

**Comment by shibing624** [comment]
1.词林词库，目前是按照一个的格式存储在xml的，如何扩展？ 这个目前采用的是知网原始数据，可以按照知网格式要求扩展。
2.没有用同义词词库，有通过word2vec生成词向量，再根据其寻找近义词数据。
3.义原数据也是知网数据，跟词林是一个体系的。
Similarity项目有关的问题，请直接在github上发起issue。

**Comment by westsince2001** [comment]
目前的词林词库，好像也已把<<哈工大信息检索研究中心同义词词林扩展版>>中的 词库也补充进去了，另外也加了新词。Gb05A04#，Gb05A07# 等。后续的继续补充能否自己来实现呢？

**Comment by shibing624** [comment]
可以的。
