### ISSUE TITLE
PhraseSimilarity 短语相似度是如何计算出来的

### ISSUE THREAD

**Issue by weixiewen** [shibing624/similarity#23]
如题，Java新手，勉强成功跑起了程序了。并代入了自己的数据进行测试。
想了解下在计算短语相似度的时候，是采用了什么算法和方法进行计算呢。

**Comment by shibing624** [comment]
PhraseSimilarity 短语相似度, 通过词与词的编辑距离简单计算得到。

**Comment by shibing624** [comment]
参考实现：https://github.com/shibing624/similarity/blob/master/src/main/java/org/xm/similarity/phrase/PhraseSimilarity.java
