### ISSUE TITLE
关于词典的问题

### ISSUE THREAD

**Issue by ifeelok** [shibing624/similarity#3]
最近我在学习如何对一个句子做情感分析，看了您的项目。有一些问题想请教一下。

1.  在`resources`目录下面的`sememe.xml`和`concept.xml`这些语料是什么语料？
2. 在`HownetWordTendency.java`文件中的`POSITIVE_SEMEMES`和`NEGATIVE_SEMEMES`您是如何挑选的？
3. **说**这个词的`negative`值是1，这个应该是有点问题。

还有一个bug：如果只分析一个单词并且该单词没有在义原中会有`java.lang.StackOverflowError`。经过调试发现问题在`ConceptSimilarity.java`文件中`getConcepts`和`autoCombineConcepts`循环调用导致：

```
    public Collection<Concept> getConcepts(String key) {
        Collection<Concept> concepts = super.getConcepts(key);
        if (StringUtil.isBlank(concepts)) {
            concepts = autoCombineConcepts(key, null);
        }
        return concepts;
    }
    public Collection<Concept> autoCombineConcepts(String newWord, Collection<Concept> refConcepts) {
        ...
        Collection<Concept> concepts = getConcepts(conceptWord);
        ...
    }
```

**Comment by shibing624** [comment]
1. 在resources目录下面的sememe.xml和concept.xml是义原数据，知网的。
2. POSITIVE_SEMEMES是积极情感数据，使用了多个积极特征词汇关联的，挑选时找的情感程度高的一级词汇。
3. 说 的情感程度看具体应用场景。
4. 谢谢提出bug，最近会有大的更新升级。
