### ISSUE TITLE
fix: Tokenizer.segment()方法BUG

### ISSUE THREAD

**Issue by wuchangtan** [shibing624/similarity#32]
.map(term -> new Word(term.word, term.nature.name()))  HanLP1.8.3已经没有.name()的方法了

**Comment by shibing624** [comment]
use 1.3.4

<dependency>
            <groupId>com.hankcs</groupId>
            <artifactId>hanlp</artifactId>
            <version>portable-1.3.4</version>
        </dependency>

其他版本切词器，自行适配。
