### ISSUE TITLE
jenkins发布失败

### ISSUE THREAD

**Issue by zyoung1212** [shibing624/similarity#46]
[ERROR] Failed to execute goal on project : Could not resolve dependencies for project com.singhand:yaoguang-event:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at com.github.shibing624:similarity:jar:1.1.6: Failed to read artifact descriptor for com.github.shibing624:similarity:jar:1.1.6: Could not transfer artifact com.github.shibing624:similarity:pom:1.1.6 from/to jitpack.io (https://jitpack.io/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by shibing624** [comment]
<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories> 这个不能用吗？没测试jenkins发布。
