### ISSUE TITLE
相似度计算比较 

### ISSUE THREAD

**Issue by Samurais** [shibing624/similarity#9]
hi，你好
我也做了一个提供中文句子相似度计算的工具包。
https://github.com/huyingxi/Synonyms

虽然你这个包提供了很多方法，但没有看到很好的例子，能提供一下么？
方便对比。

**Comment by shibing624** [comment]
test和demo都有例子。如果是比较相似度计算效果，这个比较依赖训练数据了，本身也是扩展的。看了一下你的项目，也挺好的，如果是比较同义词林的效果，可以直接用词林库。我这个工具应该是比较偏向开发者，提供一个相似度计算的方法借鉴。
